---
- name: install the time updating script
  copy:
    name: "{{ role_path }}/files/time.sh"
    dest: "/time.sh"
    mode: u=rwx,g=r,o=r
    owner: root
    group: root

- name: run the time updating script
  shell: "(! (ps -ef | grep -q time.sh | grep -v grep) && (screen -ls | grep timescreen) ) && (screen -S timescreen -X screen -t time-is-nigh -dm /time.sh) || (screen -S timescreen -t time-is-nigh -A -d -m /time.sh)"
