#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import sys, json, yaml

# read yaml from file at arg 1, dump json
print(
  json.dumps(
    yaml.load(
        open(sys.argv[1], 'r')
    ),
    indent=2
  )
)
